### ISSUE TITLE
SRGAN: BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by protoneqt** [eriklindernoren/PyTorch-GAN#120]
When I run srgan.py I have the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Python37\lib\runpy.py", line 263, in run_path
Traceback (most recent call last):
  File "E:/home/projects/deblur/git/PyTorch-GAN/implementations/srgan/srgan.py", line 98, in <module>
    for i, imgs in enumerate(dataloader):
  File "E:\home\projects\main\git\enp\venv2\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\home\projects\deblur\git\PyTorch-GAN\implementations\srgan\srgan.py", line 98, in <module>
    for i, imgs in enumerate(dataloader):
  File "E:\home\projects\main\git\enp\venv2\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "E:\home\projects\main\git\enp\venv2\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    return _MultiProcessingDataLoaderIter(self)
  File "E:\home\projects\main\git\enp\venv2\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Python37\lib\multiprocessing\process.py", line 112, in start
    w.start()
  File "C:\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    self._popen = self._Popen(self)
  File "C:\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    return Popen(process_obj)
  File "C:\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    reduction.dump(process_obj, to_child)
  File "C:\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    _check_not_importing_main()
  File "C:\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

Process finished with exit code 1

```

**Comment by zephms** [comment]
I meet the same error in running cyclegan.py

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "D:/bs/projs/zhitu/DCGAN-tensorflow-master/try04/cyclegan/cyclegan.py", line 177, in <module>
  File "D:\tools\ptyhon\lib\multiprocessing\spawn.py", line 105, in spawn_main
    for i, batch in enumerate(dataloader):
  File "D:\tools\ptyhon\lib\site-packages\torch\utils\data\dataloader.py", line 291, in __iter__
        exitcode = _main(fd)return _MultiProcessingDataLoaderIter(self)

  File "D:\tools\ptyhon\lib\multiprocessing\spawn.py", line 114, in _main
  File "D:\tools\ptyhon\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
    prepare(preparation_data)
  File "D:\tools\ptyhon\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\tools\ptyhon\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\tools\ptyhon\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\tools\ptyhon\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\tools\ptyhon\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\bs\projs\zhitu\DCGAN-tensorflow-master\try04\cyclegan\cyclegan.py", line 177, in <module>
    for i, batch in enumerate(dataloader):
  File "D:\tools\ptyhon\lib\site-packages\torch\utils\data\dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\tools\ptyhon\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
    w.start()
  File "D:\tools\ptyhon\lib\multiprocessing\process.py", line 112, in start
    w.start()
  File "D:\tools\ptyhon\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\tools\ptyhon\lib\multiprocessing\context.py", line 223, in _Popen
    self._popen = self._Popen(self)
  File "D:\tools\ptyhon\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)    return _default_context.get_context().Process._Popen(process_obj)

  File "D:\tools\ptyhon\lib\multiprocessing\context.py", line 322, in _Popen
  File "D:\tools\ptyhon\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\tools\ptyhon\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    return Popen(process_obj)
  File "D:\tools\ptyhon\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)    reduction.dump(process_obj, to_child)

  File "D:\tools\ptyhon\lib\multiprocessing\reduction.py", line 60, in dump
  File "D:\tools\ptyhon\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\tools\ptyhon\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

Process finished with exit code 1
```

Do you solved it?

**Comment by zephms** [comment]
https://github.com/pytorch/pytorch/issues/5858

**Comment by abhi-glitchhg** [comment]
..
