### ISSUE TITLE
wgan retrain_graph

### ISSUE THREAD

**Issue by alcaster** [eriklindernoren/PyTorch-GAN#6]
Running wgan.py:
```
Traceback (most recent call last):
  File "wgan.py", line 179, in <module>
    gen_validity.backward(valid)
  File "/home/alcaster/.pyenv/versions/ml/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/alcaster/.pyenv/versions/ml/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
```

My versions of packages:
torch==0.4.0
torchvision==0.2.1

**Comment by eriklindernoren** [comment]
Oh, a typo had snuck in there. Thanks!

**Comment by alcaster** [comment]
Thank you for quick response and great repo :smiley:
